FA.JustBlog/Areas/Admin/Models/HomeViewModel.cs
namespace FA.JustBlog.Areas.Admin.Models;

public class HomeViewModel
{
	public int TotalPosts { get; set; }
	public int TotalCategories { get; set; }
	public int TotalTags { get; set; }
	public int TotalComments { get; set; }
	public IEnumerable<int>? Years { get; set; }
	public IEnumerable<int>? TotalPostsOverYears { get; set; }
	public IEnumerable<string>? CategoryNames { get; set; }
	public IEnumerable<int>? TotalPostsPerCategories { get; set; }
}

FA.JustBlog/Areas/Admin/Controllers/CategoryController.cs
using AutoMapper;
using FA.JustBlog.Core.Infrastructures;
using FA.JustBlog.Core.Models.Entities;
using FA.JustBlog.Core.Models.Identities;
using FA.JustBlog.Core.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FA.JustBlog.Areas.Admin.Controllers;

[Area("Admin")]
[Route("Admin/Category")]
public class CategoryController : BaseController
{
	public CategoryController(IUnitOfWork unitOfWork, IMapper mapper, UserManager<AppUser> userManager) : base(unitOfWork, mapper, userManager)
	{
	}

	// GET: AdminController
	[Route("")]
	[Authorize(Roles = "User, Contributor, Blog_Owner")]
	public ActionResult Index()
	{
		var posts = _unitOfWork.CategoryRepository.GetAllCategories();
		return View(posts);
	}

	[Route("Delete/{id:int}")]
	[Authorize(Roles = "Blog_Owner")]
	public ActionResult Delete(int id)
	{
		try
		{
			_unitOfWork.CategoryRepository.DeleteCategory(id);
			var response = _unitOfWork.SaveChanges();
			if (response > 0)
			{
				return RedirectToAction("Index");
			}

			return NotFound();
		}
		catch (Exception ex)
		{
			Console.WriteLine(ex);
			return NotFound();
		}
	}
	
	[HttpGet]
	[Route("Create")]
	[Authorize(Roles = "Contributor, Blog_Owner")]
	public ActionResult Create()
	{
		return View();
	}

	[HttpPost]
	[Route("Create")]
	[Authorize(Roles = "Contributor, Blog_Owner")]
	[ValidateAntiForgeryToken]
	public ActionResult Create(Category category)
	{
		if (ModelState.IsValid)
		{
			if (category == null) return RedirectToAction("Index");
		
			_unitOfWork.CategoryRepository.Create(category);
			var status = _unitOfWork.SaveChanges();
			if (status > 0)
			{
				TempData["Message"] = "Category added successfully!";
				return RedirectToAction("Index");
			}

			TempData["ErrorMessage"] = "Category added failed";
			return RedirectToAction("Index");
		}

		return View();
	}
	
	[HttpGet]
	[Route("Edit/{id:int}")]
	[Authorize(Roles = "Contributor, Blog_Owner")]
	public ActionResult Edit(int id)
	{
		var category = _unitOfWork.CategoryRepository.GetById(id);
		if (category != null)
		{
			return View(category);
		}

		return NotFound();
	}
	
	[HttpPost]
	[Route("Edit/{id:int}")]
	[Authorize(Roles = "Contributor, Blog_Owner")]
	[ValidateAntiForgeryToken]
	public ActionResult Edit(int id, Category category)
	{
		if (ModelState.IsValid)
		{
			if (category == null) return RedirectToAction("Index");
		
			_unitOfWork.CategoryRepository.UpdateCategory(category);
			var status = _unitOfWork.SaveChanges();
			if (status > 0)
			{
				TempData["Message"] = "Category modified successfully!";
				return RedirectToAction("Index");
			}

			TempData["ErrorMessage"] = "Category modified failed!";
			return RedirectToAction("Index");
		}

		return View();
	}

	[HttpPost]
	[Route("Publish/{id}")]
	[Authorize(Roles = "Blog_Owner")]
	public ActionResult Publish(int id)
	{
		var category = _unitOfWork.CategoryRepository.GetById(id);
		if (category != null)
		{
			_unitOfWork.CategoryRepository.UpdateCategory(category);
			var result = _unitOfWork.SaveChanges();
			if (result > 0)
			{
				return RedirectToAction("Index");
			}

			return NotFound();
		}

		return NotFound();
	}
}

FA.JustBlog/Areas/Admin/Controllers/CommentController.cs
using AutoMapper;
using FA.JustBlog.Core.Infrastructures;
using FA.JustBlog.Core.Models.Identities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers;

[Area("Admin")]
public class CommentController : BaseController
{
    // GET: AdminController
    [Route("Admin/Comment")]
    public ActionResult Index()
    {
        return View();
    }

    public CommentController(IUnitOfWork unitOfWork, IMapper mapper, UserManager<AppUser> userManager) : base(unitOfWork, mapper, userManager)
    {
    }
}

FA.JustBlog/Areas/Admin/Controllers/HomeController.cs
using AutoMapper;
using FA.JustBlog.Areas.Admin.Models;
using FA.JustBlog.Core.Infrastructures;
using FA.JustBlog.Core.Models.Identities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers;

[Area("Admin")]
public class HomeController : BaseController
{
    public HomeController(IUnitOfWork unitOfWork, IMapper mapper, UserManager<AppUser> userManager) : base(unitOfWork, mapper, userManager)
    {
    }
    
    // GET: AdminController
    [Route("Admin")]
    public ActionResult Index()
    {
        return View(new HomeViewModel()
        {
            TotalPosts = _unitOfWork.PostRepository.GetAllPosts().Count,
            TotalCategories = _unitOfWork.CategoryRepository.GetAllCategories().Count,
            TotalTags = _unitOfWork.TagRepository.GetAllTags().Count,
            TotalComments = _unitOfWork.CommentRepository.GetAllComments().Count,
            Years = _unitOfWork.PostRepository.GetAllPosts().OrderBy(p => p.PostedOn.Year).Select(p => p.PostedOn.Year).Distinct(),
            TotalPostsOverYears = _unitOfWork.PostRepository.GetAllPosts().OrderBy(p => p.PostedOn.Year).GroupBy(p => p.PostedOn.Year).Select(group => group.Count()),
            CategoryNames = _unitOfWork.CategoryRepository.GetAllCategories().OrderBy(c => c.Id).Select(c => c.Name),
            TotalPostsPerCategories = _unitOfWork.CategoryRepository.GetAllCategories().OrderBy(c => c.Posts.Count()).Select(c => c.Posts.Count())
        });
    }
}

FA.JustBlog/Controllers/HomeController.cs
using FA.JustBlog.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using FA.JustBlog.Core.Infrastructures;
using Microsoft.AspNetCore.Authorization;

namespace FA.JustBlog.Controllers;

[Authorize]
public class HomeController : BaseController
{
    public HomeController(IUnitOfWork unitOfWork) : base(unitOfWork)
    {
    }

    public IActionResult Index()
    {
        return RedirectToAction("Index", "Post");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

FA.JustBlog/Controllers/PostController.cs
using FA.JustBlog.Core.Infrastructures;
using FA.JustBlog.Core.Models.Entities;
using FA.JustBlog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace FA.JustBlog.Controllers;

[Authorize]
public class PostController : BaseController
{
	public PostController(IUnitOfWork unitOfWork) : base(unitOfWork)
	{
	}

	// GET: PostController
	public ActionResult Index(string? search, int? page)
	{
		var posts = _unitOfWork.PostRepository.GetPublishedPosts();
		IEnumerable<Post> postsPaging;
		int pageSize = 5;
		if (!search.IsNullOrEmpty())
		{
			postsPaging =
				_unitOfWork.PostRepository.GetPaging(posts, p => p.Title.Contains(search), page ?? 1, pageSize);
		}
		else
		{
			postsPaging = _unitOfWork.PostRepository.GetPaging(posts, null, page ?? 1, pageSize);
		}

		var mostViewedPosts = _unitOfWork.PostRepository.GetAllPosts().OrderByDescending(p => p.ViewCount).Take(5);
		var latestPosts = _unitOfWork.PostRepository.GetLatestPost(5);
		var popularTags = _unitOfWork.TagRepository.GetAllTags().OrderByDescending(t => t.Count).Take(10);

		return View(new PostViewModel()
		{
			Posts = postsPaging,
			MostViewedPosts = mostViewedPosts,
			LatestPosts = latestPosts,
			PopularTags = popularTags,
			Page = page ?? 1,
			TotalPage = (int)Math.Ceiling((decimal)posts.Count / pageSize)
		});
	}

	// public ActionResult Detail(int id)
	// {
	// 	var post = _unitOfWork.PostRepository.FindPost(id);
	// 	return View(post);
	// }


	[Route("Post/{year}/{month}/{title}")]
	public ActionResult Detail(int year, int month, string title)
	{
		try
		{
			var post = _unitOfWork.PostRepository.Find(p =>
				p.PostedOn.Year == year && p.PostedOn.Month == month && p.UrlSlug == title).First();
			return View(post);
		}
		catch (Exception ex)
		{
			Console.WriteLine(ex);
			return RedirectToAction("Error", "Home");
		}
	}

	[Route("Category/{category?}/{page?}")]
	public ActionResult PostsByCategory(string? category, int? page)
	{
		ViewBag.Category = category;
		var posts = _unitOfWork.PostRepository.GetPostsByCategory(category).Where(p => p.Published).ToList();
		int pageSize = 5;
		IEnumerable<Post> postsPaging = _unitOfWork.PostRepository.GetPaging(posts, null, page ?? 1, pageSize);
		// ReSharper disable once Mvc.InvalidModelType
		return View("Index",
			new PostViewModel()
			{
				Posts = postsPaging, 
				Page = page ?? 1,
				TotalPage = (int)Math.Ceiling((decimal)posts.Count / pageSize)
			});
	}
}

FA.JustBlog/Controllers/TagController.cs
using FA.JustBlog.Core.Infrastructures;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers;

[Authorize]
public class TagController : BaseController
{
    public TagController(IUnitOfWork unitOfWork) : base(unitOfWork)
    {
    }

    // GET: TagController
    public ActionResult Index()
    {
        return View();
    }
}

FA.JustBlog/Areas/Admin/Views/Home/Index.cshtml
@model FA.JustBlog.Areas.Admin.Models.HomeViewModel

@{
    ViewData["Title"] = "Dashboard";
    Layout = "_Layout";
    
    var years = Html.Raw(Json.Serialize(Model.Years));
    var totalPostsOverYears = Html.Raw(Json.Serialize(Model.TotalPostsOverYears));
    var categoryNames = Html.Raw(Json.Serialize(Model.CategoryNames));
    var totalPostsPerCategories = Html.Raw(Json.Serialize(Model.TotalPostsPerCategories));
}

@Html.Hidden("years", years)
@Html.Hidden("totalPostsOverYears", totalPostsOverYears)
@Html.Hidden("categoryNames", categoryNames)
@Html.Hidden("totalPostsPerCategories", totalPostsPerCategories)
<div class="container-fluid px-4">
<h1 class="mt-4">Dashboard</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Dashboard</li>
</ol>
<div class="row">
    <div class="col-xl-3 col-md-6">
        <div class="card bg-primary text-white mb-4">
            <div class="w-100 card-body d-flex align-items-center">
                <div class="">Total Posts </div>
                <div class="ms-auto">@Model.TotalPosts </div>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Post" asp-action="Index">View Details</a>
                <div class="small text-white">
                    <i class="fas fa-angle-right"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-warning text-white mb-4">
            <div class="w-100 card-body d-flex align-items-center">
                <div class="">Total Categories </div>
                <div class="ms-auto">@Model.TotalCategories </div>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Category" asp-action="Index">View Details</a>
                <div class="small text-white">
                    <i class="fas fa-angle-right"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-success text-white mb-4">
            <div class="w-100 card-body d-flex align-items-center">
                <div class="">Total Tags </div>
                <div class="ms-auto">@Model.TotalTags </div>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Tag" asp-action="Index">View Details</a>
                <div class="small text-white">
                    <i class="fas fa-angle-right"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="card bg-danger text-white mb-4">
            <div class="w-100 card-body d-flex align-items-center">
                <div class="">Total Comments </div>
                <div class="ms-auto">@Model.TotalComments </div>
            </div>
            <div class="card-footer d-flex align-items-center justify-content-between">
                <a class="small text-white stretched-link" asp-area="Admin" asp-controller="Comment" asp-action="Index">View Details</a>
                <div class="small text-white">
                    <i class="fas fa-angle-right"></i>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-6">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-area me-1"></i>
                Total Posts Over Years
            </div>
            <div class="card-body">
                <canvas id="myAreaChart" width="100%" height="60"></canvas>
            </div>
        </div>
    </div>
    <div class="col-xl-6">
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-chart-bar me-1"></i>
                Total Posts By Categories
            </div>
            <div class="card-body">
                <canvas id="myPieChart" width="100%" height="60"></canvas>
            </div>
        </div>
    </div>
</div>
</div>