FA.JustBlog/Controllers/AboutController.cs
using FA.JustBlog.Core.Infrastructures;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers;

[Authorize]
public class AboutController : BaseController
{
    public AboutController(IUnitOfWork unitOfWork) : base(unitOfWork)
    {
    }
    // GET: AboutController
    public ActionResult Index()
    {
        return View();
    }
}

FA.JustBlog/Controllers/PostController.cs
using FA.JustBlog.Core.Infrastructures;
using FA.JustBlog.Core.Models.Entities;
using FA.JustBlog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace FA.JustBlog.Controllers;

[Authorize]
public class PostController : BaseController
{
	public PostController(IUnitOfWork unitOfWork) : base(unitOfWork)
	{
	}

	// GET: PostController
	public ActionResult Index(string? search, int? page)
	{
		var posts = _unitOfWork.PostRepository.GetPublishedPosts();
		IEnumerable<Post> postsPaging;
		int pageSize = 5;
		if (!search.IsNullOrEmpty())
		{
			postsPaging =
				_unitOfWork.PostRepository.GetPaging(posts, p => p.Title.Contains(search), page ?? 1, pageSize);
		}
		else
		{
			postsPaging = _unitOfWork.PostRepository.GetPaging(posts, null, page ?? 1, pageSize);
		}

		var mostViewedPosts = _unitOfWork.PostRepository.GetAllPosts().OrderByDescending(p => p.ViewCount).Take(5);
		var latestPosts = _unitOfWork.PostRepository.GetLatestPost(5);
		var popularTags = _unitOfWork.TagRepository.GetAllTags().OrderByDescending(t => t.Count).Take(10);

		return View(new PostViewModel()
		{
			Posts = postsPaging,
			MostViewedPosts = mostViewedPosts,
			LatestPosts = latestPosts,
			PopularTags = popularTags,
			Page = page ?? 1,
			TotalPage = (int)Math.Ceiling((decimal)posts.Count / pageSize)
		});
	}

	// public ActionResult Detail(int id)
	// {
	// 	var post = _unitOfWork.PostRepository.FindPost(id);
	// 	return View(post);
	// }


	[Route("Post/{year}/{month}/{title}")]
	public ActionResult Detail(int year, int month, string title)
	{
		try
		{
			var post = _unitOfWork.PostRepository.Find(p =>
				p.PostedOn.Year == year && p.PostedOn.Month == month && p.UrlSlug == title).First();
			return View(post);
		}
		catch (Exception ex)
		{
			Console.WriteLine(ex);
			return RedirectToAction("Error", "Home");
		}
	}

	[Route("Category/{category?}/{page?}")]
	public ActionResult PostsByCategory(string? category, int? page)
	{
		ViewBag.Category = category;
		var posts = _unitOfWork.PostRepository.GetPostsByCategory(category).Where(p => p.Published).ToList();
		int pageSize = 5;
		IEnumerable<Post> postsPaging = _unitOfWork.PostRepository.GetPaging(posts, null, page ?? 1, pageSize);
		// ReSharper disable once Mvc.InvalidModelType
		return View("Index",
			new PostViewModel()
			{
				Posts = postsPaging, 
				Page = page ?? 1,
				TotalPage = (int)Math.Ceiling((decimal)posts.Count / pageSize)
			});
	}
}

FA.JustBlog/Views/Shared/_Footer.cshtml
<!-- Footer-->
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Just Blog 2024</div>
            </div>
        </div>
    </div>
</footer>

FA.JustBlog/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using FA.JustBlog.Core.Models
@using FA.JustBlog.Core.Models.Entities
@{
    var categories = ViewData["Categories"] as IEnumerable<Category>;
    categories = categories.Take(3);
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FA.JustBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    @* <link rel="stylesheet" href="~/FA.JustBlog.styles.css" asp-append-version="true"/> *@
    <link rel="icon" type="image/x-icon" href="@Url.Content("~/favicon.ico")"/>
    <!-- Font Awesome icons (free version)-->
    <script src="~/fontawesome/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Just Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="About" asp-action="Index">About</a>
                </li>
                @foreach (var item in categories)
                {
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Post" asp-action="PostsByCategory" asp-route-category="@item.Name">@item.Name</a>
                    </li>
                }
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- Page Header-->
<header class="masthead" style="background-image: url(@Url.Content("/images/" + ViewData["Background"] + ".jpg"))">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                @{
                    var classHeading = ViewData["PostTitle"] == null ? "site-heading" : "post-heading";
                    <div class=@classHeading>
                        @{
                            var title = ViewData["PostTitle"] ?? "Just Blog";
                            <h1>@title</h1>
                        }
                        @{
                            var shortDescription = ViewData["ShortDescription"] == null ? "Neque porro dolor sit amet, consectetur, adipisci velit..." : "";
                            <span class="subheading">@shortDescription</span>
                        }
                        @{
                            var postMeta = ViewData["PostMeta"] ?? "";
                            <p class="post-meta">@postMeta</p>
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
@await Html.PartialAsync("_Footer")
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FA.JustBlog/Views/Shared/_PopularTags.cshtml
@model IEnumerable<FA.JustBlog.Core.Models.Entities.Tag>

<div class="">
    @foreach (var item in Model)
    {
        <div class="border border-2 text-center text-decoration-underline me-2 d-inline-block px-2 fs-6">
            #@item.Name
        </div>
    }
</div>