FA.JustBlog/Areas/Admin/Controllers/CommentController.cs
using AutoMapper;
using FA.JustBlog.Core.Infrastructures;
using FA.JustBlog.Core.Models.Identities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers;

[Area("Admin")]
public class CommentController : BaseController
{
    // GET: AdminController
    [Route("Admin/Comment")]
    public ActionResult Index()
    {
        return View();
    }

    public CommentController(IUnitOfWork unitOfWork, IMapper mapper, UserManager<AppUser> userManager) : base(unitOfWork, mapper, userManager)
    {
    }
}

FA.JustBlog/Areas/Admin/Controllers/RoleController.cs
using AutoMapper;
using FA.JustBlog.Core.Infrastructures;
using FA.JustBlog.Core.Models.Identities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers;

[Area("Admin")]
public class RoleController : BaseController
{
	public RoleController(IUnitOfWork unitOfWork, IMapper mapper, UserManager<AppUser> userManager) : base(unitOfWork, mapper, userManager)
	{
	}
	// GET: AdminController
	[Route("Admin/Role")]
	public ActionResult Index()
	{
		return View();
	}
}

FA.JustBlog/Controllers/PostController.cs
using FA.JustBlog.Core.Infrastructures;
using FA.JustBlog.Core.Models.Entities;
using FA.JustBlog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace FA.JustBlog.Controllers;

[Authorize]
public class PostController : BaseController
{
	public PostController(IUnitOfWork unitOfWork) : base(unitOfWork)
	{
	}

	// GET: PostController
	public ActionResult Index(string? search, int? page)
	{
		var posts = _unitOfWork.PostRepository.GetPublishedPosts();
		IEnumerable<Post> postsPaging;
		int pageSize = 5;
		if (!search.IsNullOrEmpty())
		{
			postsPaging =
				_unitOfWork.PostRepository.GetPaging(posts, p => p.Title.Contains(search), page ?? 1, pageSize);
		}
		else
		{
			postsPaging = _unitOfWork.PostRepository.GetPaging(posts, null, page ?? 1, pageSize);
		}

		var mostViewedPosts = _unitOfWork.PostRepository.GetAllPosts().OrderByDescending(p => p.ViewCount).Take(5);
		var latestPosts = _unitOfWork.PostRepository.GetLatestPost(5);
		var popularTags = _unitOfWork.TagRepository.GetAllTags().OrderByDescending(t => t.Count).Take(10);

		return View(new PostViewModel()
		{
			Posts = postsPaging,
			MostViewedPosts = mostViewedPosts,
			LatestPosts = latestPosts,
			PopularTags = popularTags,
			Page = page ?? 1,
			TotalPage = (int)Math.Ceiling((decimal)posts.Count / pageSize)
		});
	}

	// public ActionResult Detail(int id)
	// {
	// 	var post = _unitOfWork.PostRepository.FindPost(id);
	// 	return View(post);
	// }


	[Route("Post/{year}/{month}/{title}")]
	public ActionResult Detail(int year, int month, string title)
	{
		try
		{
			var post = _unitOfWork.PostRepository.Find(p =>
				p.PostedOn.Year == year && p.PostedOn.Month == month && p.UrlSlug == title).First();
			return View(post);
		}
		catch (Exception ex)
		{
			Console.WriteLine(ex);
			return RedirectToAction("Error", "Home");
		}
	}

	[Route("Category/{category?}/{page?}")]
	public ActionResult PostsByCategory(string? category, int? page)
	{
		ViewBag.Category = category;
		var posts = _unitOfWork.PostRepository.GetPostsByCategory(category).Where(p => p.Published).ToList();
		int pageSize = 5;
		IEnumerable<Post> postsPaging = _unitOfWork.PostRepository.GetPaging(posts, null, page ?? 1, pageSize);
		// ReSharper disable once Mvc.InvalidModelType
		return View("Index",
			new PostViewModel()
			{
				Posts = postsPaging, 
				Page = page ?? 1,
				TotalPage = (int)Math.Ceiling((decimal)posts.Count / pageSize)
			});
	}
}

FA.JustBlog/Controllers/TagController.cs
using FA.JustBlog.Core.Infrastructures;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Controllers;

[Authorize]
public class TagController : BaseController
{
    public TagController(IUnitOfWork unitOfWork) : base(unitOfWork)
    {
    }

    // GET: TagController
    public ActionResult Index()
    {
        return View();
    }
}

FA.JustBlog/Areas/Admin/Views/Shared/_Layout.cshtml
@using FA.JustBlog.Core.Models.Identities
@{
    var user = TempData["User"] as AppUser;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>@ViewData["Title"] - JustBlog</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet"/>
    <link href="~/css/admin.css" rel="stylesheet"/>
    @await RenderSectionAsync("Styles", false)
    <script src="~/fontawesome/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" asp-area="Admin" asp-controller="Home" asp-action="Index">Just Blog</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto me-3">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user fa-fw"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li>
                    <a class="dropdown-item" href="#">Settings</a>
                </li>
                <li>
                    <a class="dropdown-item" href="#">Activity Log</a>
                </li>
                <li>
                    <hr class="dropdown-divider"/>
                </li>
                <li>
                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">Logout</a>
                </li>
            </ul>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Core</div>
                    <a class="nav-link" asp-controller="Home" asp-action="Index" asp-area="Admin">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tachometer-alt"></i>
                        </div>
                        Dashboard
                    </a>
                    <div class="sb-sidenav-menu-heading">Interface</div>
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#authenticationsLayout" aria-expanded="false" aria-controls="authenticationsLayout">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-key"></i>
                        </div>
                        Authentication
                        <div class="sb-sidenav-collapse-arrow">
                            <i class="fas fa-angle-down"></i>
                        </div>
                    </a>
                    <div class="collapse" id="authenticationsLayout" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link border-start" href="#">Users</a>
                            <a class="nav-link border-start" asp-area="Admin" asp-controller="Role" asp-action="Index">Roles</a>
                        </nav>
                    </div>
                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-columns"></i>
                        </div>
                        Management
                        <div class="sb-sidenav-collapse-arrow">
                            <i class="fas fa-angle-down"></i>
                        </div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link border-start" asp-area="Admin" asp-controller="Post" asp-action="Index">Posts</a>
                            <a class="nav-link border-start" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                            <a class="nav-link border-start" asp-area="Admin" asp-controller="Tag" asp-action="Index">Tags</a>
                            <a class="nav-link border-start" asp-area="Admin" asp-controller="Comment" asp-action="Index">Comments</a>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                <div class="small">Logged in as:</div>
                @user?.Email
            </div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            @RenderBody()
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; Just Blog 2024</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="~/js/scripts.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
@await RenderSectionAsync("Scripts", false)
<script src="~/lib/demo/chart-area-demo.js"></script>
<script src="~/lib/demo/chart-bar-demo.js"></script>
<script src="~/lib/demo/chart-pie-demo.js"></script>
<script src="~/lib/datatables-simple-demo.js"></script>
</body>
</html>